server:
  port: 1222
mysql:
  user: root
  password: password
  host: localhost
  port: 3306
  dbName: shopDev
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

security:
  jwt:
    key: locser
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
log:
  log_level: debug
  file_log_name: "./storages/log/foo.txt"
  max_size: 50
  max_backups: 3
  max_age: 28
  compress: true
