server:
  port: 1222
databases:
  - user: root
    password: password
    host: localhost
    dbName: shopDev
  - user: root2
    password: password2
    host: localhost
    dbName: shopDev2
security:
  jwt:
    key: locser
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
